CREATE TABLE IF NOT EXISTS "users" (
	"id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
	"username" VARCHAR(255),
	"role" VARCHAR(255),
	"password" VARCHAR(255),
	"created_at" TIMESTAMP,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "project" (
	"id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
	"client_id" INTEGER,
	"contractor_id" INTEGER,
	"title" VARCHAR(255) NOT NULL,
	"description" TEXT,
	"budget" INTEGER,
	"updated_at" TIMESTAMP,
	"status" VARCHAR(255),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "bids" (
	"id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
	"project_id" INTEGER,
	"contractor_id" INTEGER,
	"price" INTEGER NOT NULL,
	"message" TEXT,
	"status" VARCHAR(255),
	"updated_at" TIMESTAMP,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "deliverables" (
	"id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
	"project_id" INTEGER,
	"file_name" VARCHAR(255) NOT NULL,
	"file_path" VARCHAR(255),
	"message" TEXT,
	"uploaded_at" TIMESTAMP,
	PRIMARY KEY("id")
);



ALTER TABLE "project"
ADD FOREIGN KEY("client_id") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "project"
ADD FOREIGN KEY("contractor_id") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "bids"
ADD FOREIGN KEY("project_id") REFERENCES "project"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "bids"
ADD FOREIGN KEY("contractor_id") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "deliverables"
ADD FOREIGN KEY("project_id") REFERENCES "project"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;